Buy now
Arag0rn/The-Watch-Spot pull request #12
Opened 2023-04-23 16:36 UTC by valeriycherkasov

2023-04-24 14:44 UTC, Ivan-Malakhovskyi commented
For i name не потрібно зв'язати ? 
<label for=""  ? class="modal-form-field"
        ><span class="modal-form-input-desc">Comments</span>
        <textarea
          name="" ?

2023-04-24 14:49 UTC, Ivan-Malakhovskyi requested changes

2023-04-24 14:49 UTC, Ivan-Malakhovskyi commented on src/partials/buynow.html
For i name не потрібно зв'язати ? 
<label for=""  ? class="modal-form-field"
        ><span class="modal-form-input-desc">Comments</span>
        <textarea
          name="" ?

2023-04-24 20:07 UTC, valeriycherkasov commented on src/partials/buynow.html
name підписав, for не потрібен, бо інпут вкладений в лейбл

2023-04-25 10:43 UTC, merged

2023-04-25 16:42 UTC, Ivan-Malakhovskyi reviewed
пп